#!/bin/bash

rm -f ssh*
(
   n=0
   while read host ; do
      echo "${n}: ${host}"
      (
         echo "#!/bin/sh"
         echo "ssh -C nornetpp@${host}"
      ) >ssh${n}
      chmod +x ssh${n}
      let n=$n+1
   done
) <NMS-VMs.txt
