.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2019 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd June 14, 2019
.Dt atlasmns-trace-controller 1
.Os atlasmns-trace-controller
.\" ###### Name #############################################################
.Sh NAME
.Nm atlasmns-trace-controller
.Nd Atlas/MNS Trace Controller
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm atlasmns-trace-controller
configuration_file
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm atlasmns-trace-controller
is the Atlas/MNS Trace experiment controller.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments have to be provided:
.Bl -tag -width indent
.It configuration_file
Specifies the configuration file.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It atlasmns-trace-controller atlasmns-database-configuration
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
http://www.iem.uni-due.de/~dreibh/atlasmns-trace
.br
mailto://dreibh@iem.uni-due.de
.br
