#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
import os
import datetime
from dateutil import parser

import AtlasMNSTools


# ###### Main program #######################################################
timeStamp = 1564394879579382
print(timeStamp)
dt = AtlasMNSTools.timeStampToDatetime(timeStamp)
print(dt)


dt = parser.parse('2019-07-29 10:07:59.579382')
print(dt)
timeStamp = AtlasMNSTools.datatimeToTimeStamp(dt)
print(timeStamp)
